#!/bin/sh
# Copyright 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http out/target/product/deb///www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Qualcomm blob(s) necessary for Deb hardware
rm out/target/product/deb/system/bin/ATFWD-daemon
rm out/target/product/deb/system/bin/bridgemgrd
rm out/target/product/deb/system/bin/btnvtool
rm out/target/product/deb/system/bin/diag_klog
rm out/target/product/deb/system/bin/diag_mdlog
rm out/target/product/deb/system/bin/ds_fmc_appd
rm out/target/product/deb/system/bin/efsks
rm out/target/product/deb/system/bin/hci_qcomm_init
rm out/target/product/deb/system/bin/irsc_util
rm out/target/product/deb/system/bin/ks
rm out/target/product/deb/system/bin/mm-qcamera-app
rm out/target/product/deb/system/bin/mm-qcamera-daemon
rm out/target/product/deb/system/bin/mm-qjpeg-enc-test
rm out/target/product/deb/system/bin/mm-qomx-ienc-test
rm out/target/product/deb/system/bin/mpdecision
rm out/target/product/deb/system/bin/netmgrd
rm out/target/product/deb/system/bin/nl_listener
rm out/target/product/deb/system/bin/port-bridge
rm out/target/product/deb/system/bin/qcks
rm out/target/product/deb/system/bin/qmuxd
rm out/target/product/deb/system/bin/qseecomd
rm out/target/product/deb/system/bin/radish
rm out/target/product/deb/system/bin/rmt_storage
rm out/target/product/deb/system/bin/sensors.qcom
rm out/target/product/deb/system/bin/thermald
rm out/target/product/deb/system/bin/usbhub
rm out/target/product/deb/system/bin/usbhub_init
rm out/target/product/deb/system/etc/firmware/vidc_1080p.fw
rm out/target/product/deb/system/etc/firmware/vidc.b00
rm out/target/product/deb/system/etc/firmware/vidc.b01
rm out/target/product/deb/system/etc/firmware/vidc.b02
rm out/target/product/deb/system/etc/firmware/vidc.b03
rm out/target/product/deb/system/etc/firmware/vidcfw.elf
rm out/target/product/deb/system/etc/firmware/vidc.mdt
rm out/target/product/deb/system/etc/gps.conf
rm out/target/product/deb/system/vendor/lib/egl/eglsubAndroid.so
rm out/target/product/deb/system/vendor/lib/egl/libEGL_adreno.so
rm out/target/product/deb/system/vendor/lib/egl/libGLESv1_CM_adreno.so
rm out/target/product/deb/system/vendor/lib/egl/libGLESv2_adreno.so
rm out/target/product/deb/system/vendor/lib/egl/libplayback_adreno.so
rm out/target/product/deb/system/vendor/lib/egl/libq3dtools_adreno.so
rm out/target/product/deb/system/lib/hw/flp.msm8960.so
rm out/target/product/deb/system/lib/hw/gps.msm8960.so
rm out/target/product/deb/system/lib/hw/sensors.msm8960.so
rm out/target/product/deb/system/vendor/lib/libadreno_utils.so
rm out/target/product/deb/system/lib/libaudcal.so
rm out/target/product/deb/system/lib/libaudioalsa.so
rm out/target/product/deb/system/vendor/lib/libC2D2.so
rm out/target/product/deb/system/vendor/lib/libc2d30-a3xx.so
rm out/target/product/deb/system/vendor/lib/libc2d30.so
rm out/target/product/deb/system/vendor/lib/libCB.so
rm out/target/product/deb/system/lib/libchromatix_ov5693_common.so
rm out/target/product/deb/system/lib/libchromatix_ov5693_default_video.so
rm out/target/product/deb/system/lib/libchromatix_ov5693_preview.so
rm out/target/product/deb/system/lib/libCommandSvc.so
rm out/target/product/deb/system/lib/libconfigdb.so
rm out/target/product/deb/system/lib/libcsd-client.so
rm out/target/product/deb/system/lib/libdiag.so
rm out/target/product/deb/system/lib/libdrmdiag.so
rm out/target/product/deb/system/lib/libdrmfs.so
rm out/target/product/deb/system/lib/libdrmtime.so
rm out/target/product/deb/system/lib/libdsi_netctrl.so
rm out/target/product/deb/system/lib/libdsprofile.so
rm out/target/product/deb/system/lib/libdss.so
rm out/target/product/deb/system/lib/libdsucsd.so
rm out/target/product/deb/system/lib/libdsutils.so
rm out/target/product/deb/system/lib/libDxHdcp.so
rm out/target/product/deb/system/lib/libgps.utils.so
rm out/target/product/deb/system/vendor/lib/libgsl.so
rm out/target/product/deb/system/lib/libI420colorconvert.so
rm out/target/product/deb/system/lib/libidl.so
rm out/target/product/deb/system/vendor/lib/libllvm-qcom.so
rm out/target/product/deb/system/lib/libloc_core.so
rm out/target/product/deb/system/lib/libloc_eng.so
rm out/target/product/deb/system/lib/libmm-abl.so
rm out/target/product/deb/system/lib/libmmcamera2_stats_algorithm.so
rm out/target/product/deb/system/lib/libmmcamera_image_stab.so
rm out/target/product/deb/system/lib/libmmcamera_mi1040.so
rm out/target/product/deb/system/lib/libmmcamera_ov5693.so
rm out/target/product/deb/system/lib/libmm-color-convertor.so
rm out/target/product/deb/system/lib/libnetmgr.so
rm out/target/product/deb/system/lib/liboemcrypto.so
rm out/target/product/deb/system/lib/libqcci_legacy.so
rm out/target/product/deb/system/lib/libqdi.so
rm out/target/product/deb/system/lib/libqdp.so
rm out/target/product/deb/system/lib/libqmi_cci.so
rm out/target/product/deb/system/lib/libqmi_client_qmux.so
rm out/target/product/deb/system/lib/libqmi_common_so.so
rm out/target/product/deb/system/lib/libqmi_csi.so
rm out/target/product/deb/system/lib/libqmi_csvt_srvc.so
rm out/target/product/deb/system/lib/libqmi_encdec.so
rm out/target/product/deb/system/lib/libqmiservices.so
rm out/target/product/deb/system/lib/libqmi.so
rm out/target/product/deb/system/lib/libQSEEComAPI.so
rm out/target/product/deb/system/lib/libril-qc-qmi-1.so
rm out/target/product/deb/system/lib/libril-qcril-hook-oem.so
rm out/target/product/deb/system/vendor/lib/librs_adreno_sha1.so
rm out/target/product/deb/system/vendor/lib/librs_adreno.so
rm out/target/product/deb/system/vendor/lib/libRSDriver_adreno.so
rm out/target/product/deb/system/vendor/lib/libsc-a3xx.so
rm out/target/product/deb/system/lib/libsensor1.so
rm out/target/product/deb/system/lib/libsensor_reg.so
rm out/target/product/deb/system/lib/libsensor_user_cal.so
rm out/target/product/deb/system/lib/libstagefright_hdcp.so
rm out/target/product/deb/system/lib/libxml.so
rm out/target/product/deb/system/vendor/firmware/a300_pfp.fw
rm out/target/product/deb/system/vendor/firmware/a300_pm4.fw
rm out/target/product/deb/system/vendor/firmware/discretix/dxhdcp2.b00
rm out/target/product/deb/system/vendor/firmware/discretix/dxhdcp2.b01
rm out/target/product/deb/system/vendor/firmware/discretix/dxhdcp2.b02
rm out/target/product/deb/system/vendor/firmware/discretix/dxhdcp2.b03
rm out/target/product/deb/system/vendor/firmware/discretix/dxhdcp2.mdt
rm out/target/product/deb/system/vendor/firmware/dsps.b00
rm out/target/product/deb/system/vendor/firmware/dsps.b01
rm out/target/product/deb/system/vendor/firmware/dsps.b02
rm out/target/product/deb/system/vendor/firmware/dsps.b03
rm out/target/product/deb/system/vendor/firmware/dsps.b04
rm out/target/product/deb/system/vendor/firmware/dsps.b05
rm out/target/product/deb/system/vendor/firmware/dsps.mdt
rm out/target/product/deb/system/vendor/firmware/gss.b00
rm out/target/product/deb/system/vendor/firmware/gss.b01
rm out/target/product/deb/system/vendor/firmware/gss.b02
rm out/target/product/deb/system/vendor/firmware/gss.b03
rm out/target/product/deb/system/vendor/firmware/gss.b04
rm out/target/product/deb/system/vendor/firmware/gss.b05
rm out/target/product/deb/system/vendor/firmware/gss.b06
rm out/target/product/deb/system/vendor/firmware/gss.b07
rm out/target/product/deb/system/vendor/firmware/gss.b08
rm out/target/product/deb/system/vendor/firmware/gss.b09
rm out/target/product/deb/system/vendor/firmware/gss.b10
rm out/target/product/deb/system/vendor/firmware/gss.b11
rm out/target/product/deb/system/vendor/firmware/gss.mdt
rm out/target/product/deb/system/vendor/firmware/keymaster/keymaster.b00
rm out/target/product/deb/system/vendor/firmware/keymaster/keymaster.b01
rm out/target/product/deb/system/vendor/firmware/keymaster/keymaster.b02
rm out/target/product/deb/system/vendor/firmware/keymaster/keymaster.b03
rm out/target/product/deb/system/vendor/firmware/keymaster/keymaster.mdt
rm out/target/product/deb/system/vendor/firmware/q6.b00
rm out/target/product/deb/system/vendor/firmware/q6.b01
rm out/target/product/deb/system/vendor/firmware/q6.b03
rm out/target/product/deb/system/vendor/firmware/q6.b04
rm out/target/product/deb/system/vendor/firmware/q6.b05
rm out/target/product/deb/system/vendor/firmware/q6.b06
rm out/target/product/deb/system/vendor/firmware/q6.mdt
rm out/target/product/deb/system/vendor/firmware/tzapps.b00
rm out/target/product/deb/system/vendor/firmware/tzapps.b01
rm out/target/product/deb/system/vendor/firmware/tzapps.b02
rm out/target/product/deb/system/vendor/firmware/tzapps.b03
rm out/target/product/deb/system/vendor/firmware/tzapps.mdt
rm out/target/product/deb/system/vendor/firmware/wcnss.b00
rm out/target/product/deb/system/vendor/firmware/wcnss.b01
rm out/target/product/deb/system/vendor/firmware/wcnss.b02
rm out/target/product/deb/system/vendor/firmware/wcnss.b04
rm out/target/product/deb/system/vendor/firmware/wcnss.b05
rm out/target/product/deb/system/vendor/firmware/wcnss.mdt
rm out/target/product/deb/system/vendor/lib/libdrmdecrypt.so
rm out/target/product/deb/system/vendor/lib/libgemini.so
rm out/target/product/deb/system/vendor/lib/libgeofence.so
rm out/target/product/deb/system/vendor/lib/libimage-jpeg-enc-omx-comp.so
rm out/target/product/deb/system/vendor/lib/libimage-omx-common.so
rm out/target/product/deb/system/vendor/lib/libizat_core.so
rm out/target/product/deb/system/vendor/lib/libloc_api_v02.so
rm out/target/product/deb/system/vendor/lib/libloc_ds_api.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_c2d_module.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_cpp_module.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_iface_modules.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_imglib_modules.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_isp_modules.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_pproc_modules.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_sensor_modules.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_stats_modules.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_vpe_module.so
rm out/target/product/deb/system/vendor/lib/libmmcamera2_wnr_module.so
rm out/target/product/deb/system/vendor/lib/libmmcamera_faceproc.so
rm out/target/product/deb/system/vendor/lib/libmmcamera_imglib.so
rm out/target/product/deb/system/vendor/lib/libmmipl.so
rm out/target/product/deb/system/vendor/lib/libmmjpeg.so
rm out/target/product/deb/system/vendor/lib/libmmqjpeg_codec.so
rm out/target/product/deb/system/vendor/lib/libmmstillomx.so
rm out/target/product/deb/system/vendor/lib/liboemcamera.so
rm out/target/product/deb/system/vendor/lib/libqomx_jpegenc.so
